name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install server dependencies
        run: npm ci --ignore-scripts

      - name: Build server (if applicable)
        run: npm run build --if-present

      - name: Run server tests
        run: npm test

      - name: Change to client directory
        run: cd client

      - name: Install client dependencies
        run: npm ci --ignore-scripts

      - name: Build client (if applicable)
        run: npm run build --if-present

      - name: Run client tests
        run: npm test
